import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Toilet UMD</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header/>

      <main>
        Hello there
      </main>

      
    </div>
  )
}
