import Head from 'next/head'
import Image from 'next/image'
import { Container } from 'react-bootstrap'
import Header from '../components/Header'
import Main from '../components/Main'
import Callout from '../components/Callout'
import styles from '../styles/components/Home.module.scss'
import SmallReview from '../components/SmallReview'

export default function Home() {
  const reviews = [{}, {}];

  return (
    <div className={styles.container}>
      <Head>
        <title>Toilet UMD | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <Main>
        <div className={styles.indent}>
          <h1 className={styles.welcome}>Welcome!</h1>
          <p className={styles.welcome_para}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde quisquam ratione nam dolores dolore ad accusamus consequatur qui dolorum debitis numquam magnam harum natus ducimus cupiditate repellat in aut animi, quas enim alias pariatur quaerat minima tenetur? Qui, nemo eligendi.
          </p>

          <Callout>
            <h3>Current Top Bathrooms</h3>
            {
              reviews.map((review) => (
                <SmallReview/>
              ))
            }
          </Callout>


        </div>
      </Main>

    </div>
  )
}
